### PR TITLE
FEAT：add support loongarch

### PR DESCRIPTION
**Pull request by yzewei**
Description
Added support for Ioongarch architecture for the jffi project

Context
Provide the use of jffi projects for enterprises and individuals using the Loongarch architecture series servers

### CODE REVIEW

**Comment by headius** [comment]
We previously accepted a PR to support Loongarch here: https://github.com/jnr/jffi/pull/125

What additional changes are actually needed?

@Panxuefeng-loongson Perhaps you can help here?

**Comment by Panxuefeng-loongson** [comment]
Please tell me why you're doing this. @yzewei

**Comment by Panxuefeng-loongson** [comment]
> I do not understand these changes. Many core files for jffi have been deleted, and nearly every file in the system has been touched. Please review your changes and make sure they do not delete critical files. I am happy to help get loongarch support added to jffi but this PR cannot be merged as is.

I agree with you. These changes seem unacceptable

**Comment by Panxuefeng-loongson** [comment]
Before submitting a pr, please check if loongarch is already supported. @yzewei

**Comment by yzewei** [comment]
Sorry, it was my mistake

**Pull request closed without merging**
