### PR TITLE
Enable AArch64 support

### PR DESCRIPTION
**Pull request by stooart-mon**
Just add the necessary configuration for 64-bit ARM support (AArch64).

### CODE REVIEW

**Comment by stooart-mon** [comment]
Hi, someone has come across an issue with Jenking on ARM64: https://issues.jenkins-ci.org/browse/JENKINS-30746

This is an attempt at getting jffi and jnr-ffi working for ARM64.

**Comment by headius** [comment]
Nice! Maybe I can get my Raspi3 set up to do CI 🙂

**Comment by stooart-mon** [comment]
Thanks - I'll see what I can do on my end regarding CI. I've created a pull request for jnr-ffi too that depends on this.

**Comment by fboudra** [comment]
@headius we have https://ci.linaro.org/ with ARMv8 and ARMv7 slaves if you're interested into a CI loop. I'm happy to set it up.

**Comment by headius** [comment]
@fboudra That would be great for all the JNR projects with test suites! Let me know what you need from my end!

**Pull request merged**
