### PR TITLE
bugfixes an mips start

### LINKED ISSUE #60: Foreign.getInstance().longDoubleFromString returns garbage
The failing of NumberTest.returnDefaultF128HighPrecision is buried here.
To reveal the reason, add the following test case  to ForeignTest:
`@Test public void longDoubleFromString() {
        String strValue = "1.234567890123456789";
        BigDecimal value = new BigDecimal(strValue);
        assertEquals(value.toEngineeringString(), value.toString());
        byte[] ld = new byte[Type.LONGDOUBLE.size()];
        Foreign.getInstance().longDoubleFromString(value.toEngineeringString(), ld, 0, Type.LONGDOUBLE.size());
        String strRetValue = Foreign.getInstance().longDoubleToString(ld, 0, 0);
//        String strRetValueE = Foreign.getInstance().longDoubleToEngineeringString(ld, 0, 0);
        BigDecimal retValue = new BigDecimal(strRetValue);
        BigDecimal delta = value.subtract(retValue).abs();
        assertTrue("Not equals, expected: " + value.toEngineeringString() + " but was: " + retValue.toEngineeringString(), delta.compareTo(new BigDecimal("0.0000000000000000001")) < 0);
    }`

I will poke in the c sources to figure out whats wrong...

### PR DESCRIPTION
**Pull request by aploese**
This fixes #60, #61, #51 
All native libs have to be recompiled!
mips test are passing

### CODE REVIEW

**Comment by pedrocatalao** [comment]
@aploese not sure if you noticed it but the build is failing

**Comment by aploese** [comment]
Yes, 
I know this.

Some tests on arm fail too.
I was diving in the c sources, and will investigate it later, If I can
debug that 10+ stacked defines.

**Comment by headius** [comment]
@aploese Sorry for the long delay, I did not see this until now!

Are we still good to go forward with these changes? Not much has happened in jffi since.

**Comment by aploese** [comment]
Hi Charles,

after digging into jffi,jffi-jnr,jnr-posix I thougth there must be a
simpler solution.

See this here https://github.com/aploese/jnhw.

Why?
In short:
No jffi, just direct calls to the function. There must be a direct jni
mapping for each function. The Defines are pulled in by jni calls to.
The compiling is done with autotools - so there should be not too much
trouble compiling on each platform. Try it out!
From a security point of view it should be nearly impossible to produce
a SIGSEV which terminates the whole JVM - in I.M.H.O this happend too
often with jffi.

In jffi/jffi-jnr some bugs are fixed, but some may still exist in the
native assembler generation and in the bytecode assembler generation.
Currently JNHW is my tool of choice ;-).

Am Donnerstag, den 11.04.2019, 12:19 -0700 schrieb Charles Oliver
Nutter:

**Comment by headius** [comment]
> No jffi, just direct calls to the function. There must be a direct jni
mapping for each function.

So...it's autogenerated JNI? And you have to run a native build for each platform and library you intend to use, yes?

The primary purpose of JNR, like FFI, is not having to rebuild anything for each platform and library you use. I guess that is not a requirement for you. JNHW would not work for any of the reasons I use JNR, unfortunately.

Thanks for your effort! Perhaps someone else with MIPS expertise will pick it up so we can have MIPS support in the future.

**Comment by aploese** [comment]
Am Donnerstag, den 11.04.2019, 14:05 -0700 schrieb Charles Oliver
Nutter:
> > No jffi, just direct calls to the function. There must be a direct
> > jni
> > mapping for each function.
>
> So...it's autogenerated JNI? And you have to run a native build for
> each platform and library you intend to use, yes?
No its direct and handcrafted. after that a ./configure && make is all
you need to know of.
> The primary purpose of JNR, like FFI, is not having to rebuild
> anything for each platform and library you use.
You will have to rebuild jffi for each platform you intend to run.
I think the greatest risk of using jffi-jnr is to call a vararg
function with a floating point argument and ignoring to call it right
way.
If you are that deep in the native c-code, you should be able to write
the jni wrapper code as well - otherwise it would be better to leave it
alone...
> I guess that is not a requirement for you. JNHW would not work for
> any of the reasons I use JNR, unfortunately.
> Thanks for your effort! Perhaps someone else with MIPS expertise will
> pick it up so we can have MIPS support in the future.
> —
Be aware that I fixed some bugs in my fork that I found and only
partially reported.
If I recall correctly some datatypes are not correct mapped in jffi-
jnr...

**Pull request closed without merging**
