### PR TITLE
Rebuild macOS binary

### PR DESCRIPTION
**Pull request by MSNexploder**
I rebuild the macOS binary linking against the 10.14 SDK but kept the minimum OS requirement on 10.6 (this could probably be increased as well - but I'm pretty sure it doesn't hurt us to keep it that way) using the build chain bundled with Xcode 9.4.1 (the last release with official `i386` support).

We do lose the `ppc` portion but that shouldn't be a problem. After all those are gone for ~10 years.

Apple's notarization service is happily accepting this new binary:
```
{
  "logFormatVersion": 1,
  "jobId": "20ad4cee-af3e-46ea-8ab1-76866bdd56fe",
  "status": "Accepted",
  "statusSummary": "Ready for distribution",
  "statusCode": 0,
  "archiveFilename": "jni.zip",
  "uploadDate": "2020-02-06T11:58:14Z",
  "sha256": "5f336f74f73f827742f2abf54aedee4f66af811ff10173e118b92408ef261bd6",
  "ticketContents": [
    {
      "path": "jni.zip/jni/Darwin/libjffi-1.2.2.jnilib",
      "digestAlgorithm": "SHA-256",
      "cdhash": "bad753bdbfcd3599626826a5df178452f94c10ea",
      "arch": "i386"
    },
    {
      "path": "jni.zip/jni/Darwin/libjffi-1.2.2.jnilib",
      "digestAlgorithm": "SHA-256",
      "cdhash": "dc27ee7983e0f5036683e086c5895b33e9f0e03c",
      "arch": "x86_64"
    }
  ],
  "issues": null
}
```

This should fix https://github.com/jnr/jffi/issues/74 and https://github.com/jruby/jruby/issues/6044.

While everything looks ok, I'm unsure how to properly test this.

### CODE REVIEW

**Comment by headius** [comment]
I'm fine with this if setting the minimum is sufficient for the library to work properly all the way back to 10.9 or earlier. I too have no way to test this since my only MacOS system is already on 10.14.

**Comment by headius** [comment]
From what I'm hearing and reading online, it seems like setting minimum OS version should be sufficient to maintain backward compatibility. I will check a few more resources and then proceed to merge and release this.

**Comment by headius** [comment]
Among other resources in the Apple developer documentation, I also found a number of answered questions that make me feel fairly confident about this binary. 👍

https://stackoverflow.com/questions/6591988/best-practice-for-osx-10-x-backwards-compatability

**Comment by headius** [comment]
@MSNexploder You may have better luck at this than I am, but it would be nice if we could specify the deployment target in the makefile. Do you know how to do that? My searching is bringing up nothing.

**Comment by headius** [comment]
@MSNexploder Ok I must admit I'm confused how to even build the binary using a specific MacOS target. Can you explain how you did that?

It's not that I don't trust your binary, but I'd like to build it myself and be the one blamed if something goes wrong.

**Comment by MSNexploder** [comment]
@headius No problem. Better be safe than sorry.

The Makefile is located [here](https://github.com/jnr/jffi/blob/master/jni/GNUmakefile) (which I changed slightly in https://github.com/jnr/jffi/commit/dac9360a20c333953616c83b063b6012ed1509be).
The deployment target is already set to `10.4` in [line 292](https://github.com/jnr/jffi/blob/master/jni/GNUmakefile#L292). So I think this should be fine.

Regarding the actual building of the binary:
- I switched my Java JDK to 1.8 (because of the `javah` requirement)
- Downloaded [Xcode 9.4.1](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_9.4.1/Xcode_9.4.1.xip) (pretty sure using the direct link should work without an Apple Developer ID).
- Switched to Xcode 9.4.1 using `sudo xcode-select -s /Path/to/Xcode 9.4.1.app`
- And than I just followed the `ant jar && ant archive-platform-jar && mvn package` instruction in the README.

**Comment by headius** [comment]
Thank you! I will use your instructions to modify the build permanently (so there's no chance of building for too late a version of MacOS) and install my own binary in the repo.

The XCode download did require a dev login, but apparently my Apple ID was sufficient.

**Comment by headius** [comment]
Good lord the MacOS command line build tools seem to break every time I try to use them. However I have managed to build a new library and will be pushing out jnr releases today.

**Comment by headius** [comment]
jffi 1.2.23 has been released!

**Pull request merged**
