### PR TITLE
make mvn clean package run all tests

### PR DESCRIPTION
**Pull request by mkristian**
have a look and see if this works for you as well ;)

### CODE REVIEW

**Comment by enebo** [comment]
@mkristian
/Users/enebo/work/jffi/build.xml:380: The archive jffi.jar doesn't exist
It seems to be close.

**Comment by enebo** [comment]
@mkristian https://gist.github.com/enebo/63bfd715afac81212c61 is a log.

**Comment by enebo** [comment]
```diff
diff --git a/build.xml b/build.xml
index bf50142..2021de9 100644
--- a/build.xml
+++ b/build.xml
@@ -375,7 +375,7 @@
     </zip>
   </target>
 
-  <target name="-assemble-final-jar" depends="-init-vars, -assemble-native-jar">
+  <target name="-assemble-final-jar" depends="-init-vars, -do-jar, -assemble-native-jar">
     <jar jarfile="${complete.jar}" index="true" update="true" duplicate="preserve"
          filesetmanifest="skip">
       <zipfileset src="${dist.jar}"/>
```

This builds and runs tests so now maybe I just need to make sure this is still packaged correctly.

**Comment by enebo** [comment]
hmm native does not contain any files from archive any more :)

**Comment by enebo** [comment]
Reverted my followup change and this PR for now.  Also @headius re-enabling of maven tests.  I think this works needs to be completed when there is not a deadline in the way.

**Comment by mkristian** [comment]
yeah - jumping between two build system back and forth is not really a good idea. will give it some time some time.

**Pull request merged**
