### PR TITLE
Add missing next increments in Invoker.invokeN5 where objCount <= 5

### PR DESCRIPTION
**Pull request by bendoerr**
A fix for issue #22. I briefly scanned though the rest of the class and didn't see any others missing the increment.

### CODE REVIEW

**Comment by headius** [comment]
Got left behind. Looking at it now.

**Comment by headius** [comment]
I thought I saw others but then I realized the last switch in each of these methods does not need to increment `next`. Will merge. Thank you!

**Comment by headius** [comment]
Oh, I did notice you added no test for this. If there's any way you can do that, it would be a great help. I'm not sure how you triggered this to happen...just pass <= 5 arguments for a 5 arg function?

**Comment by bendoerr** [comment]
I'll take a crack at unit test this weekend, I forget how I triggered it originally, but it was via jnr-ffi's magic.

**Comment by headius** [comment]
Great, thanks very much for your help! Sorry for the delay getting this in.

**Pull request merged**
